apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: library-platform
  labels:
    app: gateway-service
spec:
  externalName: gateway-service.library-platform.svc.cluster.local
  selector:
    app: gateway-service-container
  ports:
    - name: gateway-service
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30003
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  namespace: library-platform
  labels:
    app: gateway-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-container
  template:
    metadata:
      labels:
        app: gateway-service-container
    spec:
      containers:
        - name: gateway-service-container
          image: ${{ secrets.DOCKER_HUB_LOGIN }}/gateway-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: rest
            - containerPort: 8888
              name: config
            - containerPort: 8761
              name: discovery
          env:
            - name: CONFIG_SERVICE_HOST
              value: $(CONFIG_SERVICE_SERVICE_HOST)
            - name: CONFIG_SERVICE_PORT
              value: $(CONFIG_SERVICE_SERVICE_PORT)
            - name: EUREKA_HOST
              value: $(DISCOVERY_SERVICE_SERVICE_HOST)
            - name: EUREKA_PORT
              value: $(DISCOVERY_SERVICE_SERVICE_PORT)
            - name: PAYMENT_SERVICE_HOST
              value: $(PAYMENT_SERVICE_SERVICE_HOST)
            - name: PAYMENT_SERVICE_PORT
              value: $(PAYMENT_SERVICE_SERVICE_PORT)