apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: library-platform
  labels:
    app: payment-service
spec:
  externalName: payment-service.library-platform.svc.cluster.local
  selector:
    app: payment-service-container
  ports:
    - name: payment-service
      port: 8083
      protocol: TCP
      targetPort: 8083
      nodePort: 30005
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  namespace: library-platform
  labels:
    app: payment-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service-container
  template:
    metadata:
      labels:
        app: payment-service-container
    spec:
      containers:
        - name: payment-service-container
          image: ${{ secrets.DOCKER_HUB_LOGIN }}/payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              name: rest
            - containerPort: 8888
              name: config
            - containerPort: 8761
              name: discovery
            - containerPort: 9092
              name: kafka
          env:
            - name: CONFIG_SERVICE_HOST
              value: $(CONFIG_SERVICE_SERVICE_HOST)
            - name: CONFIG_SERVICE_PORT
              value: $(CONFIG_SERVICE_SERVICE_PORT)
            - name: EUREKA_HOST
              value: $(DISCOVERY_SERVICE_SERVICE_HOST)
            - name: EUREKA_PORT
              value: $(DISCOVERY_SERVICE_SERVICE_PORT)
            - name: SENTRY_DSN
              value: ${{ secrets.PAYMENT_SENTRY }}