apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: library-platform
  labels:
    app: product-service
spec:
  externalName: product-service.library-platform.svc.cluster.local
  selector:
    app: product-service-container
  ports:
    - name: product-service
      port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30006
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  namespace: library-platform
  labels:
    app: product-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service-container
  template:
    metadata:
      labels:
        app: product-service-container
    spec:
      containers:
        - name: product-service-container
          image: ${{ secrets.DOCKER_HUB_LOGIN }}/product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: rest
            - containerPort: 8888
              name: config
            - containerPort: 8761
              name: discovery
            - containerPort: 9092
              name: kafka
          env:
            - name: CONFIG_SERVICE_HOST
              value: $(CONFIG_SERVICE_SERVICE_HOST)
            - name: CONFIG_SERVICE_PORT
              value: $(CONFIG_SERVICE_SERVICE_PORT)
            - name: EUREKA_HOST
              value: $(DISCOVERY_SERVICE_SERVICE_HOST)
            - name: EUREKA_PORT
              value: $(DISCOVERY_SERVICE_SERVICE_PORT)