server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

properties:
  mark: profile-service

cache:
  cron:
    profile:
      clear: "0 */5 * ? * *"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

sentry:
  dsn: $PROFILE_URI
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
  debug: true
  logging:
    enabled: true
    minimum-event-level: info

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
      instance:
        preferIpAddress: true